plugins {
    id("io.dataloom.kotlin.multiplatform-library")
    alias(libs.plugins.sqldelight)
    alias(libs.plugins.android.library) apply (System.getenv("DATALOOM_ANDROID_BUILD") == "true")
}

val isAndroidBuildEnabled: Boolean =
    System.getenv("DATALOOM_ANDROID_BUILD") == "true"

kotlin {
    explicitApi()

    if (isAndroidBuildEnabled) {
        androidTarget()
    }

    sourceSets {
        commonMain {
            dependencies {
                api(project(":dataloom-model"))
                api(project(":dataloom-api"))
                implementation(libs.sqldelight.runtime)
            }
        }

        named("jvmMain") {
            dependencies {
                implementation(libs.sqldelight.sqlite.driver)
            }
        }

        findByName("androidMain")?.dependencies {
            implementation(libs.sqldelight.android.driver)
        }

        findByName("iosMain")?.dependencies {
            implementation(libs.sqldelight.native.driver)
        }
    }
}

if (isAndroidBuildEnabled) {
    // The typed `android { }` accessor is only generated by the Kotlin DSL
    // when the Android Gradle Plugin is actually applied to this project.
    // Here the plugin is only *resolved* onto the script classpath (see the
    // `apply (...)` condition above) but conditionally *applied*, so the
    // typed accessor does not exist at script-compile time even when
    // disabled. Configure the extension reflectively instead so the script
    // still compiles cleanly with DATALOOM_ANDROID_BUILD unset.
    extensions.configure<com.android.build.gradle.LibraryExtension>("android") {
        namespace = "io.dataloom.storage.sqldelight"
        compileSdk = libs.versions.android.compileSdk.get().toInt()

        defaultConfig {
            minSdk = libs.versions.android.minSdk.get().toInt()
        }
    }
}

sqldelight {
    databases {
        create("DataLoomStorageDatabase") {
            packageName.set("io.dataloom.storage.sqldelight.internal")
            // The default sqlite-3-18-dialect predates SQLite's upsert syntax
            // (ON CONFLICT ... DO UPDATE SET), which DataLoomStorage.sq uses.
            // Upsert was added in SQLite 3.24.0.
            dialect(libs.sqldelight.dialect)
        }
    }
}
