package io.dataloom.runtime.retry

import io.dataloom.api.error.DataLoomError
import io.dataloom.api.error.ErrorCategory
import io.dataloom.api.error.ErrorCode
import io.dataloom.api.error.ErrorSeverity
import io.dataloom.api.error.Recoverability
import io.dataloom.api.provider.ProviderDescriptor
import io.dataloom.api.provider.ProviderHealth
import io.dataloom.api.provider.ProviderInitializationContext
import io.dataloom.api.provider.ProviderOperationResult
import io.dataloom.api.scheduling.ScheduleCancellationRequest
import io.dataloom.api.scheduling.ScheduleReceipt
import io.dataloom.api.scheduling.ScheduleRequest
import io.dataloom.api.scheduling.SchedulerProvider

/**
 * [SchedulerProvider] decorator that enforces the configured provider timeout
 * for every lifecycle and scheduling invocation.
 *
 * The decorator preserves the delegate descriptor and exact successful or
 * canonical failure results. A timeout generated by [timeoutCoordinator] is
 * converted to a bounded canonical provider failure. Caller cancellation and
 * unexpected programming exceptions continue to propagate.
 *
 * This decorator owns provider-invocation timeout enforcement only. It does not
 * infer a workflow start time, enforce connection/request/idle boundaries, or
 * alter retry policy and scheduling semantics.
 */
public class TimeoutEnforcingSchedulerProvider(
    private val delegate: SchedulerProvider,
    private val timeoutCoordinator: RetryTimeoutCoordinator,
) : SchedulerProvider {

    override val descriptor: ProviderDescriptor
        get() = delegate.descriptor

    override suspend fun initialize(
        context: ProviderInitializationContext,
    ): ProviderOperationResult<Unit> = execute(SchedulerOperation.INITIALIZE) {
        delegate.initialize(context)
    }

    override suspend fun health(): ProviderOperationResult<ProviderHealth> =
        execute(SchedulerOperation.HEALTH) {
            delegate.health()
        }

    override suspend fun close(): ProviderOperationResult<Unit> =
        execute(SchedulerOperation.CLOSE) {
            delegate.close()
        }

    override suspend fun schedule(
        request: ScheduleRequest,
    ): ProviderOperationResult<ScheduleReceipt> = execute(SchedulerOperation.SCHEDULE) {
        delegate.schedule(request)
    }

    override suspend fun cancel(
        request: ScheduleCancellationRequest,
    ): ProviderOperationResult<Unit> = execute(SchedulerOperation.CANCEL) {
        delegate.cancel(request)
    }

    private suspend fun <T> execute(
        operation: SchedulerOperation,
        block: suspend () -> ProviderOperationResult<T>,
    ): ProviderOperationResult<T> = when (
        val result = timeoutCoordinator.execute(
            kind = RetryTimeoutKind.PROVIDER,
            operation = block,
        )
    ) {
        is RetryTimeoutExecutionResult.Completed -> result.value
        is RetryTimeoutExecutionResult.TimedOut -> ProviderOperationResult.Failure(
            SchedulerTimeoutErrors.providerTimedOut(operation),
        )
        is RetryTimeoutExecutionResult.WorkflowDeadlineExceeded -> ProviderOperationResult.Failure(
            SchedulerTimeoutErrors.workflowDeadlineExceeded(operation),
        )
        is RetryTimeoutExecutionResult.ClockRegression -> ProviderOperationResult.Failure(
            SchedulerTimeoutErrors.clockRegression(operation),
        )
    }
}

private enum class SchedulerOperation(val label: String) {
    INITIALIZE("initialize"),
    HEALTH("health"),
    CLOSE("close"),
    SCHEDULE("schedule"),
    CANCEL("cancel"),
}

private object SchedulerTimeoutErrors {
    fun providerTimedOut(operation: SchedulerOperation): DataLoomError = Error(
        code = ErrorCode("SCHEDULER_PROVIDER_TIMEOUT"),
        category = ErrorCategory.SCHEDULER,
        severity = ErrorSeverity.ERROR,
        recoverability = Recoverability.RECOVERABLE,
        message = "The scheduler provider ${operation.label} operation exceeded its configured timeout.",
    )

    fun workflowDeadlineExceeded(operation: SchedulerOperation): DataLoomError = Error(
        code = ErrorCode("SCHEDULER_WORKFLOW_DEADLINE_EXCEEDED"),
        category = ErrorCategory.SCHEDULER,
        severity = ErrorSeverity.ERROR,
        recoverability = Recoverability.NON_RECOVERABLE,
        message = "The workflow deadline expired before scheduler provider ${operation.label} completed.",
    )

    fun clockRegression(operation: SchedulerOperation): DataLoomError = Error(
        code = ErrorCode("SCHEDULER_TIMEOUT_CLOCK_REGRESSION"),
        category = ErrorCategory.STATE,
        severity = ErrorSeverity.ERROR,
        recoverability = Recoverability.NON_RECOVERABLE,
        message = "Clock regression prevented scheduler provider ${operation.label} timeout enforcement.",
    )

    private data class Error(
        override val code: ErrorCode,
        override val category: ErrorCategory,
        override val severity: ErrorSeverity,
        override val recoverability: Recoverability,
        override val message: String,
        override val cause: Throwable? = null,
    ) : DataLoomError
}
